name: Custom Android Client Generator

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Rendezvous Server'
        required: true
        default: ''
        type: string
      key:
        description: 'Public Key'
        required: true
        default: ''
        type: string
      apiServer:
        description: 'API Server'
        required: true
        default: ''
        type: string
      custom:
        description: "Custom JSON"
        required: true
        default: ''
        type: string
      uuid:
        description: "uuid of request"
        required: true
        default: ''
        type: string
      iconlink:
        description: "icon link"
        required: false
        default: 'false'
        type: string
      logolink:
        description: "logo link"
        required: false
        default: 'false'
        type: string
      appname:
        description: "app name"
        required: true
        default: 'rustdesk'
        type: string
      filename:
        description: "Filename"
        required: true
        default: 'rustdesk'
        type: string
      extras:
        description: "extra inputs in json"
        required: true
        default: '{}'
        type: string

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  CARGO_NDK_VERSION: "3.1.2"
  SCITER_ARMV7_CMAKE_VERSION: "3.29.7"
  SCITER_NASM_DEBVERSION: "2.14-1"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  ANDROID_FLUTTER_VERSION: "3.24.5" 
  FLUTTER_ELINUX_VERSION: "3.16.9"
  TAG_NAME: "${{ inputs.upload-tag }}"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "460551b0ec06be1ba6b918448bf3b0f44add813d"
  VERSION: "${{ fromJson(inputs.extras).version }}"
  NDK_VERSION: "r27c"
  ANDROID_SIGNING_KEY: "${{ secrets.ANDROID_SIGNING_KEY }}"
  MACOS_P12_BASE64: "${{ secrets.MACOS_P12_BASE64 }}"
  UPLOAD_ARTIFACT: 'true'
  SIGN_BASE_URL: "${{ secrets.SIGN_BASE_URL }}"
  STATUS_URL: "${{ secrets.GENURL }}/updategh"

jobs:
  build-android-apk:
    runs-on: ubuntu-24.04
    name: 安卓通用APK自动化生成
    steps:
      - name: "步骤1：检出代码（5%）"
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: "进度上报：5%"
        run: echo "进度5%：代码已检出"

      - name: "步骤2：环境准备（10%）"
        run: |
          echo "进度10%：开始安装依赖"
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake curl gcc-multilib git g++ g++-multilib imagemagick \
            libayatana-appindicator3-dev libasound2-dev libc6-dev libclang-dev \
            libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libgtk-3-dev libpam0g-dev libpulse-dev libva-dev libvdpau-dev \
            libxcb-randr0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxdo-dev \
            libxfixes-dev llvm-dev nasm ninja-build openjdk-17-jdk-headless \
            pkg-config tree wget
      - name: "进度上报：10%"
        run: echo "进度10%：环境准备完成"

      - name: "步骤3：安装Flutter（15%）"
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.ANDROID_FLUTTER_VERSION }}
      - name: "进度上报：15%"
        run: echo "进度15%：Flutter安装完成"

      - name: "步骤4：安装NDK工具链（20%）"
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: true
      - name: "进度上报：20%"
        run: echo "进度20%：NDK工具链准备完成"

      - name: "步骤5：设置环境变量（25%）"
        run: echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
      - name: "进度上报：25%"
        run: echo "进度25%：JAVA_HOME设置完成"

      - name: "步骤6：拉取Flutter依赖（30%）"
        run: flutter pub get
      - name: "进度上报：30%"
        run: echo "进度30%：Flutter依赖拉取完成"

      - name: "步骤7：修改图标（35%）"
        if: ${{ inputs.iconlink != 'false' }}
        continue-on-error: true
        run: |
          wget -O ./res/icon.png "${{ fromJson(inputs.iconlink).url }}/get_png?filename=${{ fromJson(inputs.iconlink).file}&uuid=${{ fromJson(inputs.iconlink).uuid }}"
          convert ./res/icon.png -resize 256x256 ./res/icon-256.png
          pushd ./flutter
          flutter pub get
          dart run flutter_launcher_icons
          popd
      - name: "进度上报：35%"
        run: echo "进度35%：图标修改完成"

      - name: "步骤8：替换参数与定制（40%）"
        shell: bash
        run: |
          sed -i -e 's|rs-ny.rustdesk.com|${{ inputs.server }}|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|${{ inputs.key }}|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|https://admin.rustdesk.com|${{ inputs.apiServer }}|' ./src/common.rs
      - name: "进度上报：40%"
        run: echo "进度40%：定制参数应用完成"

      - name: "步骤9：应用定制应用名称与UI（45%）"
        if: inputs.appname != 'rustdesk'
        shell: bash
        run: |
          sed -i 's|name = "RustDesk"|name = "${{ inputs.appname }}"|' ./Cargo.toml
          sed -i 's|RustDesk|${{ inputs.appname }}|' ./flutter/android/app/src/main/res/values/strings.xml
          sed -i -e "s|title: 'RustDesk'|title: '${{ inputs.appname }}'|" ./flutter/lib/main.dart
          sed -i 's|android:label="RustDesk"|android:label="${{ inputs.appname }}"|' ./flutter/android/app/src/main/AndroidManifest.xml
      - name: "进度上报：45%"
        run: echo "进度45%：应用名称和UI定制完成"

      - name: "步骤10：写入自定义配置文件（50%）"
        run: echo -n "${{ inputs.custom }}" > ./flutter/assets/custom.txt
      - name: "进度上报：50%"
        run: echo "进度50%：自定义配置文件写入完成"

      - name: "步骤11：安装Rust工具链并依赖（55%）"
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: "rustfmt"
      - name: "进度上报：55%"
        run: echo "进度55%：Rust工具链准备完成"

      - name: "步骤12：安装cargo-ndk（60%）"
        run: cargo install cargo-ndk --version ${{ env.CARGO_NDK_VERSION }} --locked
      - name: "进度上报：60%"
        run: echo "进度60%：cargo-ndk安装完成"

      - name: "步骤13：构建Rust库（65%）"
        run: |
          rustup target add aarch64-linux-android
          cargo ndk -t arm64-v8a -o ./flutter/android/app/src/main/jniLibs build --release
      - name: "进度上报：65%"
        run: echo "进度65%：Rust库构建完成"

      - name: "步骤14：构建APK包（70%）"
        run: |
          pushd flutter
          flutter build apk --release
          popd
      - name: "进度上报：70%"
        run: echo "进度70%：APK构建完成"

      - name: "步骤15：签名APK（75%）"
        uses: r0adkll/sign-android-release@v1
        if: env.ANDROID_SIGNING_KEY != null
        with:
          releaseDirectory: ./flutter/build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
      - name: "进度上报：75%"
        run: echo "进度75%：APK签名完成"

      - name: "步骤16：上传APK到服务器（80%）"
        if: ${{ fromJson(inputs.extras).rdgen == 'true' }}
        run: |
          curl -i -X POST -H "Content-Type: multipart/form-data" -H "Authorization: Bearer ${{ fromJson(inputs.extras).token }}" -F "file=@./flutter/build/app/outputs/flutter-apk/app-release.apk" "${{ env.STATUS_URL }}"
      - name: "步骤16：上传APK到API（80%）"
        if: ${{ fromJson(inputs.extras).rdgen == 'false' }}
        run: |
          curl -i -X POST -H "Content-Type: multipart/form-data" -H "Authorization: Bearer ${{ fromJson(inputs.extras).token }}" -F "file=@./flutter/build/app/outputs/flutter-apk/app-release.apk" "${{ inputs.apiServer }}/api/updategh"
      - name: "进度上报：80%"
        run: echo "进度80%：APK上传完成"

      - name: "步骤17：上传构建产物到Actions（90%）"
        uses: actions/upload-artifact@v4
        with:
          name: 安卓APK
          path: ./flutter/build/app/outputs/flutter-apk/app-release.apk
      - name: "进度上报：90%"
        run: echo "进度90%：构建产物上传完成"

      - name: "步骤18：流程完成（100%）"
        run: echo "进度100%：通用安卓APK生成流程全部完成！"
      - name: "失败回调"
        if: failure()
        run: echo "流水线失败，生成失败，请重新尝试"
      - name: "取消回调"
        if: cancelled()
        run: echo "流水线已取消，生成失败，请重新尝试"